/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.courses.pb138.j2014.projects.soxc.GUI;

import cz.muni.fi.courses.pb138.j2014.projects.soxc.Options;
import cz.muni.fi.courses.pb138.j2014.projects.soxc.Soxc;
import cz.muni.fi.courses.pb138.j2014.projects.soxc.difftree.DocumentDiffTree;
import cz.muni.fi.courses.pb138.j2014.projects.soxc.difftree.consumers.JustDocumentDiffTreeConsumer;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.UIManager; 
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import org.w3c.dom.Document;
import org.xml.sax.SAXException;

/**
 *
 * @author Jakub Kremláček
 */
public class GUISelector extends javax.swing.JFrame {

    /**
     * Creates new form GUIMain
     */
    public static String newline = System.getProperty("line.separator");
    
    public GUISelector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void setPath(javax.swing.JTextField jTextField) {
        JFileChooser chooser = new JFileChooser();
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.addChoosableFileFilter(new FileFilter() {
            public String getDescription() {
                return "XML Documents (*.xml)";
            }

            public boolean accept(File f) {
                if (f.isDirectory()) {
                    return true;
                } else {
                    return f.getName().toLowerCase().endsWith(".xml");
                }
            }
        });
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filepath = f.getAbsolutePath();
        jTextField.setText(filepath);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pathfileLeft = new javax.swing.JTextField();
        leftFileLabel = new javax.swing.JLabel();
        rightFileLabel = new javax.swing.JLabel();
        pathfileRight = new javax.swing.JTextField();
        browseButtonLeft = new javax.swing.JButton();
        browseButtonRight = new javax.swing.JButton();
        selectFilesLabel = new javax.swing.JLabel();
        runButton = new javax.swing.JButton();
        checkBoxIgnoreElementOrder = new javax.swing.JCheckBox();
        checkBoxIgnoreAttrInSimilar = new javax.swing.JCheckBox();
        optionsLabel = new javax.swing.JLabel();
        checkBoxIgnoreNamespaceURI = new javax.swing.JCheckBox();
        checkBoxIgnorePrefix = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SOXC GUI");
        setResizable(false);

        pathfileLeft.setEditable(false);
        pathfileLeft.setText("path");

        leftFileLabel.setText("XML File 1");

        rightFileLabel.setText("XML File 2");

        pathfileRight.setEditable(false);
        pathfileRight.setText("path");

        browseButtonLeft.setText("Browse");
        browseButtonLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonLeftActionPerformed(evt);
            }
        });

        browseButtonRight.setText("Browse");
        browseButtonRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonRightActionPerformed(evt);
            }
        });

        selectFilesLabel.setText("Select files:");

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        checkBoxIgnoreElementOrder.setText("Ignore element order");
        checkBoxIgnoreElementOrder.setToolTipText("");
        checkBoxIgnoreElementOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxIgnoreElementOrderActionPerformed(evt);
            }
        });

        checkBoxIgnoreAttrInSimilar.setText("Ignore attributes in similarity");
        checkBoxIgnoreAttrInSimilar.setToolTipText("");

        optionsLabel.setText("Additional options:");

        checkBoxIgnoreNamespaceURI.setText("Ignore namespace URI");

        checkBoxIgnorePrefix.setText("Ignore prefix");
        checkBoxIgnorePrefix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxIgnorePrefixActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxIgnoreNamespaceURI)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(checkBoxIgnoreElementOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkBoxIgnoreAttrInSimilar, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkBoxIgnorePrefix)
                                        .addComponent(selectFilesLabel)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(leftFileLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pathfileLeft, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                                .addComponent(rightFileLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pathfileRight, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(browseButtonLeft)
                                                .addComponent(browseButtonRight)))
                                        .addComponent(optionsLabel))
                                    .addGap(20, 20, 20)))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(runButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectFilesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(leftFileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathfileLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButtonLeft))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightFileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pathfileRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButtonRight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(optionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxIgnoreElementOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxIgnoreAttrInSimilar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxIgnorePrefix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxIgnoreNamespaceURI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void browseButtonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonLeftActionPerformed
        setPath(pathfileLeft);
    }//GEN-LAST:event_browseButtonLeftActionPerformed

    private void browseButtonRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonRightActionPerformed
        setPath(pathfileRight);
    }//GEN-LAST:event_browseButtonRightActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        try {
           
            if(!"path".equals(pathfileLeft.getText()) && !"path".equals(pathfileRight.getText())) {
                this.setVisible(false);
                DocumentBuilderFactory factory1 = DocumentBuilderFactory.newInstance();
                DocumentBuilder builder1 = factory1.newDocumentBuilder();       
                Document docLeft = builder1.parse(pathfileLeft.getText());

                DocumentBuilderFactory factory2 = DocumentBuilderFactory.newInstance();
                DocumentBuilder builder2 = factory2.newDocumentBuilder();       
                Document docRight = builder2.parse(pathfileRight.getText());

                JustDocumentDiffTreeConsumer consumer = new JustDocumentDiffTreeConsumer();
                Options options = new Options(
                        checkBoxIgnoreElementOrder.isSelected(),
                        checkBoxIgnoreAttrInSimilar.isSelected(),
                        checkBoxIgnoreNamespaceURI.isSelected(),
                        checkBoxIgnorePrefix.isSelected());

                boolean equals = Soxc.diffDocuments(docLeft, docRight, options, consumer);

                if (equals) {
                    String message = "XML files are equal.";
                    JOptionPane.showMessageDialog(new JFrame(), message, "SOXC", JOptionPane.INFORMATION_MESSAGE);
                    System.exit(0);
                } else {
                    DocumentDiffTree tree = consumer.getDocumentDiffTree();
                    GUIDisplay frame = new GUIDisplay(tree);
                    frame.display();
                }
            } else {
                String message = "Pathfiles have to be set.";
                JOptionPane.showMessageDialog(new JFrame(), message, "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (ParserConfigurationException | SAXException | IOException ex) {
            Logger.getLogger(GUISelector.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_runButtonActionPerformed

    private void checkBoxIgnoreElementOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxIgnoreElementOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxIgnoreElementOrderActionPerformed

    private void checkBoxIgnorePrefixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxIgnorePrefixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxIgnorePrefixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(
            UIManager.getSystemLookAndFeelClassName()); 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISelector().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseButtonLeft;
    private javax.swing.JButton browseButtonRight;
    private javax.swing.JCheckBox checkBoxIgnoreAttrInSimilar;
    private javax.swing.JCheckBox checkBoxIgnoreElementOrder;
    private javax.swing.JCheckBox checkBoxIgnoreNamespaceURI;
    private javax.swing.JCheckBox checkBoxIgnorePrefix;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel leftFileLabel;
    private javax.swing.JLabel optionsLabel;
    private javax.swing.JTextField pathfileLeft;
    private javax.swing.JTextField pathfileRight;
    private javax.swing.JLabel rightFileLabel;
    private javax.swing.JButton runButton;
    private javax.swing.JLabel selectFilesLabel;
    // End of variables declaration//GEN-END:variables
}
